# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('residential_address', models.CharField(max_length=200)),
                ('child_name', models.CharField(max_length=100)),
                ('child_date_of_birth', models.DateField()),
                ('desired_join_date', models.DateField()),
                ('desired_child_drop_off_time', models.TimeField()),
                ('desired_child_pick_up_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
