# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('residential_address', models.CharField(max_length=200)),
                ('position_of_interest', models.CharField(max_length=100)),
                ('desired_join_date', models.DateField()),
                ('motivation', models.TextField()),
                ('work_history', models.TextField()),
                ('academic_qualifications', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
